services:
  app:
    build: .
    ports:
      - "8080:5005"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SA_PASSWORD=${SA_PASSWORD}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - PROD_DB_USER=${PROD_DB_USER}
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge